@echo off


cls
echo .....................................................
echo .....................................................
echo ...Script para resolver problemas no CITRIX..........
echo .........Criado por Gleriston Sampaio................
echo .....................................................
echo .....................................................

timeout 1 > NUL
echo Finalizado o CITRIX...
timeout 1 > NUL
taskkill /IM AuthManSvr.exe /f
taskkill /IM CtxWebBrowser.exe /f
cls

echo .....................................................
echo .....................................................
echo ...Script para resolver problemas no CITRIX..........
echo .........Criado por Gleriston Sampaio................
echo .....................................................
echo .....................................................

echo CITRIX Finalizado!


timeout 5 > NUL
echo Limpando o CITRIX...

DEL /S /Q /F "%Userprofile%\AppData\Local\Citrix\*.*"   
FOR /D %%d IN ("%Userprofile%\AppData\Local\Citrix\*.*") DO RD /S /Q "%%d" 
if exist "%profiles%\%%u\AppData\Local\Citrix" 
if exist "%profiles%\%%u\AppData\Local\Citrix" cd "%profiles%\%%u\AppData\Local\Citrix"
if exist "%profiles%\%%u\AppData\Local\Citrix" del *.* /F /S /Q /A: R /A: H /A: A
if exist "%profiles%\%%u\AppData\Local\Citrix" rmdir /s /q "%profiles%\%%u\AppData\Local\Citrix"

cls
timeout 1 > NUL
echo .....................................................
echo .....................................................
echo ...Script para resolver problemas no CITRIX..........
echo .........Criado por Gleriston Sampaio................
echo .....................................................
echo .....................................................

echo CITRIX Finalizado!
echo CITRIX Limpo!

timeout 2 > NUL
echo Resetando o CITRIX...

"C:\Program Files (x86)\Citrix\ICA Client\SelfServicePlugin\CleanUp.exe" -cleanUser

timeout 3 > NUL
echo .....................................................
echo .....................................................
echo ...Script para resolver problemas no CITRIX..........
echo .........Criado por Gleriston Sampaio................
echo .....................................................
echo .....................................................

echo CITRIX Finalizado!
echo CITRIX Limpo!
echo CITRIX Iniciando!